/**
 * Arduino Preprocessor
 *
 * Converts Arduino .ino sketch files to standard C++ files.
 * Arduino uses simplified syntax that requires transformation before compilation:
 * - Function prototypes must be generated
 * - Arduino.h must be included
 * - Multiple .ino files must be concatenated
 * - A main() wrapper calling setup() and loop() must be generated
 */

export interface PreprocessResult {
  code: string; // The transformed C++ code
  mainFile: string; // Generated main.cpp content
  warnings: string[]; // Any preprocessing warnings
}

export class ArduinoPreprocessor {
  /**
   * Preprocess Arduino sketch to C++
   */
  preprocess(inoContent: string): PreprocessResult {
    const warnings: string[] = [];

    // Extract function prototypes (except setup and loop)
    const prototypes = this.extractFunctionPrototypes(inoContent);

    // Build the final C++ code
    let code = "";

    // Add Arduino.h include
    code += "#include <Arduino.h>\n\n";

    // Add function prototypes
    if (prototypes.length > 0) {
      code += "// Function prototypes\n";
      for (const prototype of prototypes) {
        code += prototype + "\n";
      }
      code += "\n";
    }

    // Add the sketch code
    code += inoContent;

    // Generate main.cpp
    const mainFile = this.generateMain();

    return {
      code,
      mainFile,
      warnings,
    };
  }

  /**
   * Extract function prototypes from code
   * Don't include setup() and loop() - those are extern declarations
   */
  private extractFunctionPrototypes(code: string): string[] {
    const prototypes: string[] = [];

    // Remove comments to avoid matching in comments
    const codeWithoutComments = this.removeComments(code);

    // Regular expression to match function definitions
    // Matches: returnType functionName(parameters) {
    // Handles various C++ return types including pointers, references, templates, multi-word types
    // Return type can be: "int", "unsigned long*", "const char&", etc.
    const functionRegex =
      /^\s*(?:(?:static|inline|virtual|extern)\s+)*((?:const\s+)?(?:unsigned\s+)?(?:signed\s+)?\w+(?:\s*\*|\s*&)?(?:\s*<[^>]+>)?)\s+(\w+)\s*\(([^)]*)\)\s*(?:const)?\s*\{/gm;

    let match;
    while ((match = functionRegex.exec(codeWithoutComments)) !== null) {
      const returnType = match[1].trim();
      const functionName = match[2].trim();
      const params = match[3].trim();

      // Skip setup() and loop() - they're Arduino special functions
      if (functionName === "setup" || functionName === "loop") {
        continue;
      }

      // Build prototype
      const prototype = `${returnType} ${functionName}(${params});`;
      prototypes.push(prototype);
    }

    return prototypes;
  }

  /**
   * Remove C/C++ style comments from code
   */
  private removeComments(code: string): string {
    // Remove single-line comments
    let result = code.replace(/\/\/.*$/gm, "");

    // Remove multi-line comments
    result = result.replace(/\/\*[\s\S]*?\*\//g, "");

    return result;
  }

  /**
   * Generate Arduino runtime main.cpp
   */
  generateMain(): string {
    return `// Arduino runtime main.cpp
// Generated by BattleForge Arduino preprocessor

#include <Arduino.h>

// External declarations for user functions
extern "C" void setup();
extern "C" void loop();

int main(void) {
  // Initialize Arduino runtime
  init();

  // Call user setup function
  setup();

  // Main loop
  for (;;) {
    loop();

    // Allow background tasks to run
    if (serialEventRun) serialEventRun();
  }

  return 0;
}
`;
  }

  /**
   * Combine multiple .ino files into one
   * Main .ino file first, then others alphabetically
   */
  combineSketchFiles(files: Map<string, string>): string {
    if (files.size === 0) {
      return "";
    }

    // Find the main sketch file (same name as folder or first alphabetically)
    const fileNames = Array.from(files.keys()).sort();

    let combined = "";

    // Add all files in alphabetical order
    for (const fileName of fileNames) {
      const content = files.get(fileName) || "";

      combined += `// ===== ${fileName} =====\n`;
      combined += content;
      combined += "\n\n";
    }

    return combined;
  }
}
