"use client";

/**
 * Analysis Context - Global state for firmware analysis results
 *
 * Provides indexed access to analysis data from WASM decoder.
 * All heavy lifting (decoding, xref extraction) is done in Rust.
 * This is just a thin indexing layer for fast lookups in the UI.
 *
 * Persistence:
 * - Analysis results are automatically saved to IndexedDB
 * - Results are loaded on startup if available
 * - User comments and function renames are persisted
 */

import React, {
  createContext,
  useContext,
  useState,
  useCallback,
  useMemo,
  useEffect,
  useRef,
} from "react";
import type {
  AnalysisResults,
  XrefResult,
  Loop,
  VectorTableEntry,
} from "../wasmAnalyzer";
import { XrefType } from "../wasmAnalyzer";
import {
  getAnalysisDatabase,
  type DbFunction,
  type DbComment,
  type DbXref,
  type CommentType,
} from "../db/AnalysisDatabase";
import { useProjectOptional } from "./ProjectContext";

/**
 * Comment with type information
 */
export interface Comment {
  text: string;
  type: CommentType;
  timestamp: number;
}

/**
 * Argument annotation for a function call
 */
export interface ArgAnnotation {
  call_address: number;
  function_target: number;
  args: Array<[number, string]>;
}

/**
 * Function information derived from call xrefs
 */
export interface FunctionInfo {
  address: number;
  name: string; // "sub_1000" or user-renamed
  callers: number[]; // Addresses that call this function
  callees: number[]; // Addresses this function calls
  xref_count: number; // Total xrefs to this function

  // Extended analysis data from WASM analyzer
  end_address?: number;
  stack_frame_size?: number;
  stack_vars?: Array<{
    function_start: number;
    offset: number;
    size: number;
    access_type: number;
  }>;
  arg_annotations?: ArgAnnotation[];
  complexity?: number;
}

/**
 * Analysis context state
 */
interface AnalysisContextState {
  // Raw analysis results from WASM
  results: AnalysisResults | null;

  // Firmware info
  baseAddress: number;
  firmwareSize: number;

  // Indexed lookups (built from results)
  xrefsTo: Map<number, XrefResult[]>; // address → xrefs pointing TO this address
  xrefsFrom: Map<number, XrefResult[]>; // address → xrefs FROM this address
  functions: Map<number, FunctionInfo>; // address → function info
  comments: Map<number, Map<CommentType, Comment>>; // address → comment type → comment
  loops: Loop[]; // all detected loops from CFG analysis
  vectorTable: VectorTableEntry[]; // vector table entries from WASM analysis

  // Methods
  setAnalysisResults: (
    results: AnalysisResults,
    baseAddr: number,
    size: number,
  ) => void;
  clearAnalysis: () => void;
  getXrefsTo: (address: number) => XrefResult[];
  getXrefsFrom: (address: number) => XrefResult[];
  getFunctionAt: (address: number) => FunctionInfo | null;
  renameFunction: (address: number, newName: string) => void;
  getComment: (address: number, type?: CommentType) => Comment | null;
  getCommentsAt: (address: number) => Map<CommentType, Comment>;
  setComment: (address: number, text: string, type: CommentType) => void;
  deleteComment: (address: number, type: CommentType) => void;
  getAllRepeatableComments: () => Map<number, Comment>;
  getLoopsInRange: (startAddr: number, endAddr: number) => Loop[];
  getArgAnnotation: (callAddress: number) => ArgAnnotation | null;
  isAnalyzed: () => boolean;

  // Vector table methods
  getVectorTable: () => VectorTableEntry[];
  getHandlerByVector: (vectorNum: number) => VectorTableEntry | null;
  renameVectorHandler: (vectorNum: number, newName: string) => void;

  // Database operations
  saveToDatabase: () => Promise<void>;
  loadFromDatabase: () => Promise<boolean>;
  exportDatabase: () => Promise<void>;
  importDatabase: (file: File) => Promise<void>;
  clearDatabase: () => Promise<void>;
  clearAutoGeneratedData: () => Promise<void>;
}

const AnalysisContext = createContext<AnalysisContextState | undefined>(
  undefined,
);

/**
 * Build lookup indexes from analysis results
 *
 * This is the only place we process the raw WASM results.
 * We build fast lookup tables for the UI.
 */
function buildIndexes(results: AnalysisResults) {
  const xrefsTo = new Map<number, XrefResult[]>();
  const xrefsFrom = new Map<number, XrefResult[]>();
  const functions = new Map<number, FunctionInfo>();

  // Index all xrefs
  results.xrefs.forEach((xref) => {
    // Index by from_addr (who calls/references this)
    if (!xrefsFrom.has(xref.from_addr)) {
      xrefsFrom.set(xref.from_addr, []);
    }
    xrefsFrom.get(xref.from_addr)!.push(xref);

    // Index by to_addr (what this references)
    if (!xrefsTo.has(xref.to_addr)) {
      xrefsTo.set(xref.to_addr, []);
    }
    xrefsTo.get(xref.to_addr)!.push(xref);
  });

  // Use actual functions from WASM analyzer if available
  if (results.functions && results.functions.length > 0) {
    results.functions.forEach((func) => {
      functions.set(func.start_address, {
        address: func.start_address,
        name:
          func.name || `sub_${func.start_address.toString(16).toUpperCase()}`,
        callers: func.callers,
        callees: func.callees,
        xref_count: func.callers.length,
        // Preserve all extended analysis data
        end_address: func.end_address ?? undefined,
        stack_frame_size: func.stack_frame_size,
        stack_vars: func.stack_vars,
        arg_annotations: func.arg_annotations,
        complexity: func.complexity,
      });
    });
  } else {
    // Fallback: infer functions from call xrefs
    results.xrefs.forEach((xref) => {
      if (xref.xref_type === XrefType.Call) {
        if (!functions.has(xref.to_addr)) {
          functions.set(xref.to_addr, {
            address: xref.to_addr,
            name: `sub_${xref.to_addr.toString(16).toUpperCase()}`,
            callers: [],
            callees: [],
            xref_count: 0,
          });
        }

        const func = functions.get(xref.to_addr)!;
        if (!func.callers.includes(xref.from_addr)) {
          func.callers.push(xref.from_addr);
        }
        func.xref_count++;
      }
    });

    // Build callees list for each function
    functions.forEach((func, funcAddr) => {
      const callsFrom = xrefsFrom.get(funcAddr) || [];
      func.callees = callsFrom
        .filter((xref) => xref.xref_type === XrefType.Call)
        .map((xref) => xref.to_addr);
    });
  }

  return { xrefsTo, xrefsFrom, functions };
}

/**
 * Analysis Context Provider
 */
export function AnalysisProvider({ children }: { children: React.ReactNode }) {
  const [results, setResults] = useState<AnalysisResults | null>(null);
  const [baseAddress, setBaseAddress] = useState(0);
  const [firmwareSize, setFirmwareSize] = useState(0);
  const [comments, setComments] = useState<
    Map<number, Map<CommentType, Comment>>
  >(new Map());
  const [isLoading, setIsLoading] = useState(true);

  // Database instance
  const dbRef = useRef(getAnalysisDatabase());
  const saveTimeoutRef = useRef<NodeJS.Timeout | null>(null);

  // Project manager for saving analysis metadata
  const projectContext = useProjectOptional();

  // Build indexes when results change
  const { xrefsTo, xrefsFrom, functions } = useMemo(() => {
    if (!results) {
      return {
        xrefsTo: new Map(),
        xrefsFrom: new Map(),
        functions: new Map(),
      };
    }

    return buildIndexes(results);
  }, [results]);

  const setAnalysisResults = useCallback(
    (newResults: AnalysisResults, baseAddr: number, size: number) => {
      // Set results immediately (non-blocking)
      setResults(newResults);
      setBaseAddress(baseAddr);
      setFirmwareSize(size);

      // Load user data asynchronously in the background (don't block UI)
      const db = dbRef.current;
      Promise.all([db.getUserRenamedFunctions(), db.getAllComments()])
        .then(([userRenamedFunctions, dbComments]) => {
          // Apply user renames to functions
          if (newResults.functions && userRenamedFunctions.size > 0) {
            newResults.functions.forEach((func) => {
              const userRename = userRenamedFunctions.get(func.start_address);
              if (userRename) {
                func.name = userRename;
              }
            });
            // Trigger re-render with updated function names
            setResults({ ...newResults });
            console.log(
              `[AnalysisContext] Restored ${userRenamedFunctions.size} function renames`,
            );
          }

          // Load comments
          const commentsMap = new Map<number, Map<CommentType, Comment>>();
          dbComments.forEach((dbComment) => {
            let commentMap = commentsMap.get(dbComment.address);
            if (!commentMap) {
              commentMap = new Map<CommentType, Comment>();
              commentsMap.set(dbComment.address, commentMap);
            }

            commentMap.set(dbComment.comment_type, {
              text: dbComment.text,
              type: dbComment.comment_type,
              timestamp: dbComment.timestamp,
            });
          });
          setComments(commentsMap);

          if (dbComments.length > 0) {
            console.log(
              `[AnalysisContext] Restored ${dbComments.length} comments`,
            );
          }
        })
        .catch((error) => {
          console.error("[AnalysisContext] Error loading user data:", error);
        });
    },
    [],
  );

  const clearAnalysis = useCallback(() => {
    setResults(null);
    setBaseAddress(0);
    setFirmwareSize(0);
    setComments(new Map());
  }, []);

  const getXrefsTo = useCallback(
    (address: number): XrefResult[] => {
      return xrefsTo.get(address) || [];
    },
    [xrefsTo],
  );

  const getXrefsFrom = useCallback(
    (address: number): XrefResult[] => {
      return xrefsFrom.get(address) || [];
    },
    [xrefsFrom],
  );

  const getFunctionAt = useCallback(
    (address: number): FunctionInfo | null => {
      return functions.get(address) || null;
    },
    [functions],
  );

  const renameFunction = useCallback(
    (address: number, newName: string) => {
      const func = functions.get(address);
      if (!func) return;

      // Update function name in memory
      func.name = newName;

      // Update in results if available (to persist across reloads)
      if (results?.functions) {
        const resultFunc = results.functions.find(
          (f) => f.start_address === address,
        );
        if (resultFunc) {
          resultFunc.name = newName;
        }
      }

      // Trigger re-render by creating new results object
      if (results) {
        setResults({ ...results });
      }

      // Save to database asynchronously (debounced via auto-save)
      const db = dbRef.current;
      db.saveFunction({
        address: func.address,
        name: newName,
        callers: func.callers,
        callees: func.callees,
        xref_count: func.xref_count,
        is_user_renamed: true, // Mark as user-renamed to preserve during re-analysis
      }).catch((error) => {
        console.error(
          "[AnalysisContext] Failed to save renamed function:",
          error,
        );
      });
    },
    [functions, results],
  );

  const getComment = useCallback(
    (address: number, type: CommentType = "standard"): Comment | null => {
      const commentMap = comments.get(address);
      return commentMap?.get(type) || null;
    },
    [comments],
  );

  const getCommentsAt = useCallback(
    (address: number): Map<CommentType, Comment> => {
      return comments.get(address) || new Map();
    },
    [comments],
  );

  const setComment = useCallback(
    (address: number, text: string, type: CommentType) => {
      setComments((prev) => {
        const newComments = new Map(prev);
        // Create a NEW Map from the existing one (or create empty) to avoid mutation
        const oldCommentMap = newComments.get(address);
        const commentMap = oldCommentMap
          ? new Map(oldCommentMap)
          : new Map<CommentType, Comment>();

        commentMap.set(type, {
          text,
          type,
          timestamp: Date.now(),
        });

        newComments.set(address, commentMap);
        return newComments;
      });

      // Immediately save comment to database (user data is critical)
      const db = dbRef.current;
      db.saveComments([
        {
          id: `${address}_${type}`,
          address,
          text,
          comment_type: type,
          timestamp: Date.now(),
        },
      ]).catch((error) => {
        console.error("[AnalysisContext] Failed to save comment:", error);
      });
    },
    [],
  );

  const deleteComment = useCallback((address: number, type: CommentType) => {
    setComments((prev) => {
      const newComments = new Map(prev);
      const oldCommentMap = newComments.get(address);

      if (oldCommentMap) {
        // Create a NEW Map to avoid mutation
        const commentMap = new Map(oldCommentMap);
        commentMap.delete(type);

        if (commentMap.size === 0) {
          newComments.delete(address);
        } else {
          newComments.set(address, commentMap);
        }
      }

      return newComments;
    });

    // Immediately delete comment from database
    const db = dbRef.current;
    db.deleteComment(address, type).catch((error) => {
      console.error("[AnalysisContext] Failed to delete comment:", error);
    });
  }, []);

  const getAllRepeatableComments = useCallback((): Map<number, Comment> => {
    const repeatableComments = new Map<number, Comment>();

    comments.forEach((commentMap, address) => {
      const repeatableComment = commentMap.get("repeatable");
      if (repeatableComment) {
        repeatableComments.set(address, repeatableComment);
      }
    });

    return repeatableComments;
  }, [comments]);

  const getLoopsInRange = useCallback(
    (startAddr: number, endAddr: number): Loop[] => {
      if (!results || !results.loops) {
        return [];
      }

      // Return loops that overlap with the visible range
      return results.loops.filter((loop) => {
        // Check if loop header or back edge is in range
        const headerInRange =
          loop.header_addr >= startAddr && loop.header_addr <= endAddr;
        const backEdgeInRange =
          loop.back_edge_addr >= startAddr && loop.back_edge_addr <= endAddr;

        // Or check if any body address is in range
        const bodyOverlaps = loop.body_addrs.some(
          (addr) => addr >= startAddr && addr <= endAddr,
        );

        return headerInRange || backEdgeInRange || bodyOverlaps;
      });
    },
    [results],
  );

  const getArgAnnotation = useCallback(
    (callAddress: number): ArgAnnotation | null => {
      // Search through all functions to find one that has arg_annotations containing this call address
      for (const func of functions.values()) {
        if (func.arg_annotations && func.arg_annotations.length > 0) {
          const annotation = func.arg_annotations.find(
            (ann: ArgAnnotation) => ann.call_address === callAddress,
          );
          if (annotation) {
            return annotation;
          }
        }
      }
      return null;
    },
    [functions],
  );

  const isAnalyzed = useCallback(() => {
    return results !== null;
  }, [results]);

  // ============================================================================
  // Vector Table Operations
  // ============================================================================

  const getVectorTable = useCallback((): VectorTableEntry[] => {
    return results?.vector_table || [];
  }, [results]);

  const getHandlerByVector = useCallback(
    (vectorNum: number): VectorTableEntry | null => {
      const vectorTable = results?.vector_table || [];
      return (
        vectorTable.find((entry) => entry.vector_number === vectorNum) || null
      );
    },
    [results],
  );

  const renameVectorHandler = useCallback(
    (vectorNum: number, newName: string) => {
      if (!results?.vector_table) return;

      const entry = results.vector_table.find(
        (e) => e.vector_number === vectorNum,
      );
      if (entry) {
        entry.handler_name = newName;
        // Trigger re-render by creating new results object
        setResults({ ...results });
      }
    },
    [results],
  );

  // ============================================================================
  // Database Operations
  // ============================================================================

  /**
   * Save analysis data to IndexedDB
   */
  const saveToDatabase = useCallback(async () => {
    if (!results) {
      return;
    }

    try {
      const db = dbRef.current;

      // Convert functions Map to array of DbFunction
      const dbFunctions: DbFunction[] = Array.from(functions.values()).map(
        (func) => ({
          address: func.address,
          name: func.name,
          callers: func.callers,
          callees: func.callees,
          xref_count: func.xref_count,
        }),
      );

      // Convert comments Map to array of DbComment (flatten multi-type structure)
      const dbComments: DbComment[] = [];
      comments.forEach((commentMap, address) => {
        commentMap.forEach((comment) => {
          dbComments.push({
            id: `${address}_${comment.type}`,
            address,
            text: comment.text,
            comment_type: comment.type,
            timestamp: comment.timestamp,
          });
        });
      });

      // Convert xrefs to array of DbXref
      const dbXrefs: DbXref[] = results.xrefs.map((xref) => ({
        id: `${xref.from_addr}_${xref.to_addr}_${xref.xref_type}`,
        from_addr: xref.from_addr,
        to_addr: xref.to_addr,
        xref_type: xref.xref_type,
        instruction: xref.instruction,
        operands: xref.operands,
      }));

      // Convert vector table to array of DbVectorTableEntry
      const dbVectorTable =
        results.vector_table?.map((entry) => ({
          vector_number: entry.vector_number,
          handler_address: entry.handler_address,
          handler_name: entry.handler_name,
          is_valid: entry.is_valid,
        })) || [];

      // Save all data to database
      await Promise.all([
        db.saveFunctions(dbFunctions),
        db.saveComments(dbComments),
        db.saveXrefs(dbXrefs),
        db.saveVectorTable(dbVectorTable),
        db.setMetadata("baseAddress", baseAddress),
        db.setMetadata("firmwareSize", firmwareSize),
        db.setMetadata("totalInstructions", results.total_instructions),
        db.setMetadata("analysisTime", results.analysis_time_ms),
        db.setMetadata("lastModified", Date.now()),
      ]);

      // Update project analysis metadata (if project context is available)
      if (projectContext) {
        const projectManager = projectContext.projectManager;
        const cachedFirmware = projectManager.getCachedFirmware();

        projectManager.updateAnalysis({
          analyzedAt: new Date().toISOString(),
          analysisVersion: 1,
          mdbDatabaseName: "battlemagic-analysis",
          stats: {
            totalInstructions: results.total_instructions,
            functionCount: dbFunctions.length,
            xrefCount: dbXrefs.length,
            analysisTimeMs: results.analysis_time_ms,
          },
          firmwareHashAtAnalysis: cachedFirmware?.hash,
        });

        // IMPORTANT: Immediately save project to localStorage (don't wait for auto-save interval)
        // This ensures metadata is persisted before user reloads
        projectManager.saveToLocalStorage();

        console.log(
          "[AnalysisContext] Updated and saved project with analysis metadata",
        );
      }
    } catch (error) {
      console.error("[AnalysisContext] Failed to save to database:", error);
      throw error;
    }
  }, [results, functions, comments, baseAddress, firmwareSize, projectContext]);

  /**
   * Load analysis data from IndexedDB
   */
  const loadFromDatabase = useCallback(async (): Promise<boolean> => {
    try {
      const db = dbRef.current;

      // Check if database has any data
      const hasData = await db.hasAnalysis();
      if (!hasData) {
        setIsLoading(false);
        return false;
      }

      // Load all data from database
      const [
        dbFunctions,
        dbComments,
        dbXrefs,
        dbVectorTable,
        dbBaseAddress,
        dbFirmwareSize,
        dbTotalInstructions,
        dbAnalysisTime,
      ] = await Promise.all([
        db.getAllFunctions(),
        db.getAllComments(),
        db.getAllXrefs(),
        db.getAllVectorTableEntries(),
        db.getMetadata<number>("baseAddress"),
        db.getMetadata<number>("firmwareSize"),
        db.getMetadata<number>("totalInstructions"),
        db.getMetadata<number>("analysisTime"),
      ]);

      // Convert DbFunction[] to functions array
      const functions = dbFunctions.map((dbFunc) => ({
        start_address: dbFunc.address,
        name: dbFunc.name,
        callers: dbFunc.callers,
        callees: dbFunc.callees,
        // Extended fields may not be in database (they come from WASM analyzer)
        // Provide default values that match FunctionInfo type
        end_address: null,
        stack_frame_size: 0,
        stack_vars: [],
        arg_annotations: [],
        complexity: 0,
      }));

      // Convert DbXref[] to XrefResult[]
      const xrefs: XrefResult[] = dbXrefs.map((xref) => ({
        from_addr: xref.from_addr,
        to_addr: xref.to_addr,
        xref_type: xref.xref_type,
        instruction: xref.instruction,
        operands: xref.operands,
      }));

      // Calculate unique targets from xrefs
      const uniqueTargets = new Set(xrefs.map((x) => x.to_addr)).size;

      // Find address range
      const addresses = xrefs.flatMap((x) => [x.from_addr, x.to_addr]);
      const startAddress =
        addresses.length > 0 ? Math.min(...addresses) : dbBaseAddress || 0;
      const endAddress =
        addresses.length > 0 ? Math.max(...addresses) : dbBaseAddress || 0;

      // Reconstruct AnalysisResults
      const analysisResults: AnalysisResults = {
        xrefs,
        loops: [],
        functions,
        total_instructions: dbTotalInstructions || 0,
        analysis_time_ms: dbAnalysisTime || 0,
        unique_targets: uniqueTargets,
        start_address: startAddress,
        end_address: endAddress,
        vector_table: dbVectorTable,
      };

      // Convert comments to nested Map structure
      const commentsMap = new Map<number, Map<CommentType, Comment>>();
      dbComments.forEach((dbComment) => {
        let commentMap = commentsMap.get(dbComment.address);
        if (!commentMap) {
          commentMap = new Map<CommentType, Comment>();
          commentsMap.set(dbComment.address, commentMap);
        }

        commentMap.set(dbComment.comment_type, {
          text: dbComment.text,
          type: dbComment.comment_type,
          timestamp: dbComment.timestamp,
        });
      });

      // Set state
      setResults(analysisResults);
      setBaseAddress(dbBaseAddress || 0);
      setFirmwareSize(dbFirmwareSize || 0);
      setComments(commentsMap);

      setIsLoading(false);
      return true;
    } catch (error) {
      console.error("[AnalysisContext] Failed to load from database:", error);
      setIsLoading(false);
      return false;
    }
  }, []);

  /**
   * Export database to .mdb file
   */
  const exportDatabase = useCallback(async () => {
    try {
      const db = dbRef.current;
      const timestamp = new Date()
        .toISOString()
        .replace(/[:.]/g, "-")
        .slice(0, -5);
      const filename = `battlemagic_${timestamp}.mdb`;
      await db.downloadMdb(filename);
    } catch (error) {
      console.error("[AnalysisContext] Failed to export database:", error);
      throw error;
    }
  }, []);

  /**
   * Import database from .mdb file
   */
  const importDatabase = useCallback(
    async (file: File) => {
      try {
        const db = dbRef.current;
        await db.uploadMdb(file);

        // Reload data from database
        await loadFromDatabase();
      } catch (error) {
        console.error("[AnalysisContext] Failed to import database:", error);
        throw error;
      }
    },
    [loadFromDatabase],
  );

  /**
   * Clear database
   */
  const clearDatabase = useCallback(async () => {
    try {
      const db = dbRef.current;
      await db.clear();
    } catch (error) {
      console.error("[AnalysisContext] Failed to clear database:", error);
      throw error;
    }
  }, []);

  /**
   * Clear auto-generated data only (preserve user comments and renames)
   * Used when re-analyzing firmware to refresh xrefs, loops, etc.
   */
  const clearAutoGeneratedData = useCallback(async () => {
    try {
      const db = dbRef.current;
      await db.clearAutoGeneratedData();
      console.log(
        "[AnalysisContext] Cleared auto-generated data, preserved user data",
      );
    } catch (error) {
      console.error(
        "[AnalysisContext] Failed to clear auto-generated data:",
        error,
      );
      throw error;
    }
  }, []);

  /**
   * Debounced auto-save to database
   */
  const scheduleSave = useCallback(() => {
    // Clear existing timeout
    if (saveTimeoutRef.current) {
      clearTimeout(saveTimeoutRef.current);
    }

    // Schedule new save after 2 seconds of inactivity
    saveTimeoutRef.current = setTimeout(() => {
      saveToDatabase().catch((error) => {
        console.error("[AnalysisContext] Auto-save failed:", error);
      });
    }, 2000);
  }, [saveToDatabase]);

  // ============================================================================
  // Effects
  // ============================================================================

  // Load from database on mount
  useEffect(() => {
    loadFromDatabase().catch((error) => {
      console.error("[AnalysisContext] Failed to load from database:", error);
    });
  }, [loadFromDatabase]);

  // Auto-save when data changes
  useEffect(() => {
    if (!isLoading && results) {
      scheduleSave();
    }
  }, [results, comments, functions, isLoading, scheduleSave]);

  // Cleanup timeout on unmount
  useEffect(() => {
    return () => {
      if (saveTimeoutRef.current) {
        clearTimeout(saveTimeoutRef.current);
      }
    };
  }, []);

  const value: AnalysisContextState = {
    results,
    baseAddress,
    firmwareSize,
    xrefsTo,
    xrefsFrom,
    functions,
    comments,
    loops: results?.loops || [],
    vectorTable: results?.vector_table || [],
    setAnalysisResults,
    clearAnalysis,
    getXrefsTo,
    getXrefsFrom,
    getFunctionAt,
    renameFunction,
    getComment,
    getCommentsAt,
    setComment,
    deleteComment,
    getAllRepeatableComments,
    getLoopsInRange,
    getArgAnnotation,
    isAnalyzed,
    getVectorTable,
    getHandlerByVector,
    renameVectorHandler,
    saveToDatabase,
    loadFromDatabase,
    exportDatabase,
    importDatabase,
    clearDatabase,
    clearAutoGeneratedData,
  };

  return (
    <AnalysisContext.Provider value={value}>
      {children}
    </AnalysisContext.Provider>
  );
}

/**
 * Hook to use analysis context
 */
export function useAnalysis() {
  const context = useContext(AnalysisContext);
  if (!context) {
    throw new Error("useAnalysis must be used within AnalysisProvider");
  }
  return context;
}

/**
 * Hook to check if analysis is available (without throwing)
 */
export function useAnalysisOptional() {
  return useContext(AnalysisContext);
}
