/**
 * LinkerScriptGenerator
 *
 * Generates GNU ld linker scripts from platform memory configuration and device sizes.
 * Based on real linker scripts from:
 * - STMicroelectronics/cmsis_device_f1 (STM32)
 * - raspberrypi/pico-sdk (RP2040)
 * - NordicSemiconductor/nrfx (nRF52)
 */

import type {
  PlatformMemoryConfig,
  PlatformLinkerConfig,
  DeviceMemorySizes,
  BoardMemoryOverride,
} from "../registry/types";

export interface LinkerScriptConfig {
  /** Platform memory configuration (origins, attributes) */
  memory: PlatformMemoryConfig;
  /** Linker configuration (entry point, template) */
  linker: PlatformLinkerConfig;
  /** Device memory sizes */
  deviceSizes: DeviceMemorySizes;
  /** Optional board-level memory overrides */
  boardOverride?: BoardMemoryOverride;
  /** Device name for comments */
  deviceName?: string;
}

/**
 * Formats a number as a size string (e.g., 65536 -> "64K")
 */
function formatSize(bytes: number): string {
  if (bytes >= 1024 * 1024 && bytes % (1024 * 1024) === 0) {
    return `${bytes / (1024 * 1024)}M`;
  }
  if (bytes >= 1024 && bytes % 1024 === 0) {
    return `${bytes / 1024}K`;
  }
  return `${bytes}`;
}

/**
 * Calculates end of RAM for stack pointer
 */
function calculateRamEnd(origin: string, size: number): string {
  const originNum = parseInt(origin, 16);
  const end = originNum + size - 1;
  return `0x${end.toString(16).toUpperCase()}`;
}

/**
 * Generates a GNU ld linker script from configuration
 */
export class LinkerScriptGenerator {
  /**
   * Generate a complete linker script from configuration
   */
  generate(config: LinkerScriptConfig): string {
    const { linker, deviceSizes, boardOverride, deviceName } = config;

    // Apply board overrides to device sizes
    const finalSizes: DeviceMemorySizes = {
      ...deviceSizes,
      FLASH: boardOverride?.FLASH ?? deviceSizes.FLASH,
      RAM: boardOverride?.RAM ?? deviceSizes.RAM,
    };

    // Select template based on configuration
    switch (linker.template) {
      case "arm-cortex-m":
      case "arm-cortex-m0":
      case "arm-cortex-m4f":
        return this.generateArmCortexM(config, finalSizes, deviceName);
      case "rp2040":
        return this.generateRP2040(config, finalSizes, deviceName);
      case "xtensa-esp32":
        return this.generateXtensaESP32(config, finalSizes, deviceName);
      default:
        return this.generateArmCortexM(config, finalSizes, deviceName);
    }
  }

  /**
   * ARM Cortex-M template (STM32, nRF52)
   * Based on STMicroelectronics/cmsis_device_f1 linker scripts
   */
  private generateArmCortexM(
    config: LinkerScriptConfig,
    sizes: DeviceMemorySizes,
    deviceName?: string
  ): string {
    const { memory, linker, boardOverride } = config;
    const flashOrigin = memory.regions.FLASH.origin;
    const ramOrigin = memory.regions.RAM.origin;
    const flashSize = formatSize(sizes.FLASH);
    const ramSize = formatSize(sizes.RAM);

    // Calculate stack end (top of RAM)
    const stackEnd =
      memory.stack?.endSymbol || "_estack";
    const stackEndValue = calculateRamEnd(ramOrigin, sizes.RAM);

    const minHeapSize = memory.heap?.minSize ?? 0x200;
    const minStackSize = memory.stack?.minSize ?? 0x400;

    const script = `/**
 * Linker Script for ${deviceName || "ARM Cortex-M Device"}
 * Generated by BattleForge LinkerScriptGenerator
 *
 * Memory Configuration:
 *   FLASH: ${flashOrigin}, ${flashSize}
 *   RAM:   ${ramOrigin}, ${ramSize}
${boardOverride?.note ? ` * Note: ${boardOverride.note}\n` : ""} */

/* Entry Point */
ENTRY(${linker.entry})

/* Highest address of the user mode stack */
${stackEnd} = ${stackEndValue};    /* end of RAM */

/* Generate error if heap+stack don't fit in RAM */
_Min_Heap_Size = 0x${minHeapSize.toString(16)};      /* required heap  */
_Min_Stack_Size = 0x${minStackSize.toString(16)};    /* required stack */

/* Memory Definitions */
MEMORY
{
  FLASH (${memory.regions.FLASH.attr})  : ORIGIN = ${flashOrigin}, LENGTH = ${flashSize}
  RAM (${memory.regions.RAM.attr})      : ORIGIN = ${ramOrigin}, LENGTH = ${ramSize}
}

/* Sections */
SECTIONS
{
  /* Interrupt Vector Table - must be at start of FLASH */
  .isr_vector :
  {
    . = ALIGN(4);
    KEEP(*(.isr_vector))
    . = ALIGN(4);
  } >FLASH

  /* Program code and constants */
  .text :
  {
    . = ALIGN(4);
    *(.text)
    *(.text*)
    *(.glue_7)         /* glue arm to thumb code */
    *(.glue_7t)        /* glue thumb to arm code */
    *(.eh_frame)

    KEEP(*(.init))
    KEEP(*(.fini))

    . = ALIGN(4);
    _etext = .;
  } >FLASH

  /* Read-only data */
  .rodata :
  {
    . = ALIGN(4);
    *(.rodata)
    *(.rodata*)
    . = ALIGN(4);
  } >FLASH

  /* ARM exception handling */
  .ARM.extab :
  {
    *(.ARM.extab* .gnu.linkonce.armextab.*)
  } >FLASH

  .ARM :
  {
    __exidx_start = .;
    *(.ARM.exidx*)
    __exidx_end = .;
  } >FLASH

  /* Constructors */
  .preinit_array :
  {
    PROVIDE_HIDDEN(__preinit_array_start = .);
    KEEP(*(.preinit_array*))
    PROVIDE_HIDDEN(__preinit_array_end = .);
  } >FLASH

  .init_array :
  {
    PROVIDE_HIDDEN(__init_array_start = .);
    KEEP(*(SORT(.init_array.*)))
    KEEP(*(.init_array*))
    PROVIDE_HIDDEN(__init_array_end = .);
  } >FLASH

  .fini_array :
  {
    PROVIDE_HIDDEN(__fini_array_start = .);
    KEEP(*(SORT(.fini_array.*)))
    KEEP(*(.fini_array*))
    PROVIDE_HIDDEN(__fini_array_end = .);
  } >FLASH

  /* Used by startup to initialize data */
  _sidata = LOADADDR(.data);

  /* Initialized data - loaded to FLASH, copied to RAM at startup */
  .data :
  {
    . = ALIGN(4);
    _sdata = .;
    *(.data)
    *(.data*)
    . = ALIGN(4);
    _edata = .;
  } >RAM AT> FLASH

  /* Uninitialized data - zeroed at startup */
  .bss :
  {
    . = ALIGN(4);
    _sbss = .;
    __bss_start__ = _sbss;
    *(.bss)
    *(.bss*)
    *(COMMON)
    . = ALIGN(4);
    _ebss = .;
    __bss_end__ = _ebss;
  } >RAM

  /* User heap and stack check */
  ._user_heap_stack :
  {
    . = ALIGN(8);
    PROVIDE(end = .);
    PROVIDE(_end = .);
    . = . + _Min_Heap_Size;
    . = . + _Min_Stack_Size;
    . = ALIGN(8);
  } >RAM

  /* Remove debug information from standard libraries */
  /DISCARD/ :
  {
    libc.a(*)
    libm.a(*)
    libgcc.a(*)
  }

  .ARM.attributes 0 : { *(.ARM.attributes) }
}
`;

    return script;
  }

  /**
   * RP2040 template
   * Based on raspberrypi/pico-sdk linker scripts
   */
  private generateRP2040(
    config: LinkerScriptConfig,
    sizes: DeviceMemorySizes,
    deviceName?: string
  ): string {
    const { memory, linker } = config;
    const flashOrigin = memory.regions.FLASH.origin;
    const ramOrigin = memory.regions.RAM.origin;
    const flashSize = formatSize(sizes.FLASH);
    const ramSize = formatSize(sizes.RAM);

    // RP2040 has special scratch memory regions
    const scratchXOrigin = "0x20040000";
    const scratchYOrigin = "0x20041000";
    const scratchSize = "4K";

    return `/**
 * Linker Script for ${deviceName || "RP2040"}
 * Generated by BattleForge LinkerScriptGenerator
 *
 * Memory Configuration:
 *   FLASH:     ${flashOrigin}, ${flashSize}
 *   RAM:       ${ramOrigin}, ${ramSize}
 *   SCRATCH_X: ${scratchXOrigin}, ${scratchSize}
 *   SCRATCH_Y: ${scratchYOrigin}, ${scratchSize}
 */

/* Entry Point */
ENTRY(${linker.entry})

/* Memory Definitions */
MEMORY
{
  FLASH(${memory.regions.FLASH.attr})     : ORIGIN = ${flashOrigin}, LENGTH = ${flashSize}
  RAM(${memory.regions.RAM.attr})         : ORIGIN = ${ramOrigin}, LENGTH = ${ramSize}
  SCRATCH_X(rwx) : ORIGIN = ${scratchXOrigin}, LENGTH = ${scratchSize}
  SCRATCH_Y(rwx) : ORIGIN = ${scratchYOrigin}, LENGTH = ${scratchSize}
}

SECTIONS
{
  /* Second stage bootloader (256 bytes) */
  .boot2 : {
    __boot2_start__ = .;
    KEEP(*(.boot2))
    __boot2_end__ = .;
  } > FLASH

  ASSERT(__boot2_end__ - __boot2_start__ == 256,
    "ERROR: Pico second stage bootloader must be 256 bytes")

  /* Vector table */
  .vectors : {
    __vectors_start__ = .;
    KEEP(*(.vectors))
    __vectors_end__ = .;
  } > FLASH

  /* Reset handler and binary info */
  .binary_info_header : {
    __binary_info_header_start = .;
    KEEP(*(.binary_info.header))
    __binary_info_header_end = .;
  } > FLASH

  /* Program code */
  .text : {
    __text_start__ = .;
    *(.text)
    *(.text*)
    *(.rodata)
    *(.rodata*)
    *(.srodata*)
    . = ALIGN(4);
    __text_end__ = .;
  } > FLASH

  /* ARM exception handling */
  .ARM.extab : {
    *(.ARM.extab* .gnu.linkonce.armextab.*)
  } > FLASH

  .ARM : {
    __exidx_start = .;
    *(.ARM.exidx*)
    __exidx_end = .;
  } > FLASH

  /* Binary info tables */
  .binary_info : {
    __binary_info_start = .;
    KEEP(*(.binary_info.keep.*))
    *(.binary_info.*)
    __binary_info_end = .;
  } > FLASH

  /* Data initialization */
  __data_lma = .;

  /* Initialized data */
  .data : {
    __data_start__ = .;
    *(.data)
    *(.data*)
    . = ALIGN(4);
    __data_end__ = .;
  } > RAM AT> FLASH

  /* Uninitialized data */
  .bss (NOLOAD) : {
    . = ALIGN(4);
    __bss_start__ = .;
    *(.bss)
    *(.bss*)
    *(COMMON)
    . = ALIGN(4);
    __bss_end__ = .;
  } > RAM

  /* Scratch memory for core 0 */
  .scratch_x : {
    __scratch_x_start__ = .;
    *(.scratch_x.*)
    . = ALIGN(4);
    __scratch_x_end__ = .;
  } > SCRATCH_X AT> FLASH

  __scratch_x_lma = LOADADDR(.scratch_x);

  /* Scratch memory for core 1 */
  .scratch_y : {
    __scratch_y_start__ = .;
    *(.scratch_y.*)
    . = ALIGN(4);
    __scratch_y_end__ = .;
  } > SCRATCH_Y AT> FLASH

  __scratch_y_lma = LOADADDR(.scratch_y);

  /* Heap and stack */
  .heap (NOLOAD) : {
    __heap_start__ = .;
    __end__ = .;
    end = .;
    KEEP(*(.heap*))
    . = ORIGIN(RAM) + LENGTH(RAM) - 0x400;
    __heap_end__ = .;
  } > RAM

  /* Stack at end of RAM */
  .stack (NOLOAD) : {
    __stack_start__ = .;
    . = . + 0x400;
    __stack_end__ = .;
  } > RAM

  __StackTop = ORIGIN(RAM) + LENGTH(RAM);
  __StackLimit = __StackTop - 0x400;
  PROVIDE(__stack = __StackTop);
}
`;
  }

  /**
   * Xtensa ESP32 template
   * ESP32 uses a different architecture but similar concepts
   */
  private generateXtensaESP32(
    config: LinkerScriptConfig,
    sizes: DeviceMemorySizes,
    deviceName?: string
  ): string {
    const { linker } = config;
    const flashSize = formatSize(sizes.FLASH);
    const ramSize = formatSize(sizes.RAM);

    // ESP32 has complex memory layout with IRAM, DRAM, etc.
    // This is a simplified version - actual ESP-IDF uses multiple ld files
    return `/**
 * Linker Script for ${deviceName || "ESP32"}
 * Generated by BattleForge LinkerScriptGenerator
 *
 * Note: ESP32 has a complex memory architecture with IRAM, DRAM, and
 * external flash. This is a simplified linker script for basic use.
 * For full ESP-IDF compatibility, use the ESP-IDF build system.
 *
 * Memory Configuration:
 *   FLASH: ${flashSize}
 *   DRAM:  ${ramSize}
 */

/* Entry Point */
ENTRY(${linker.entry})

/* Memory Definitions */
MEMORY
{
  /* Internal SRAM for data */
  dram0_0_seg (RW)     : ORIGIN = 0x3FFB0000, LENGTH = 176K
  /* Internal SRAM for instructions */
  iram0_0_seg (RX)     : ORIGIN = 0x40080000, LENGTH = 128K
  /* RTC fast memory */
  rtc_iram_seg (RWX)   : ORIGIN = 0x400C0000, LENGTH = 8K
  /* RTC slow memory */
  rtc_slow_seg (RW)    : ORIGIN = 0x50000000, LENGTH = 8K
  /* External flash (code execution via cache) */
  irom_seg (RX)        : ORIGIN = 0x400D0000, LENGTH = 3M
  /* External flash (data via cache) */
  drom_seg (R)         : ORIGIN = 0x3F400000, LENGTH = 4M
}

SECTIONS
{
  /* Vectors */
  .iram.vectors : {
    _init_start = ABSOLUTE(.);
    KEEP(*(.vectors))
    _init_end = ABSOLUTE(.);
  } > iram0_0_seg

  /* IRAM code */
  .iram.text : {
    _iram_text_start = ABSOLUTE(.);
    *(.iram1 .iram1.*)
    *(.iram.text .iram.text.*)
    _iram_text_end = ABSOLUTE(.);
  } > iram0_0_seg

  /* Flash code */
  .flash.text : {
    _stext = .;
    *(.literal .text .literal.* .text.*)
    _etext = .;
  } > irom_seg

  /* Flash rodata */
  .flash.rodata : {
    _rodata_start = .;
    *(.rodata .rodata.*)
    _rodata_end = .;
  } > drom_seg

  /* DRAM data */
  .dram0.data : {
    _data_start = ABSOLUTE(.);
    *(.data .data.*)
    _data_end = ABSOLUTE(.);
  } > dram0_0_seg

  /* DRAM bss */
  .dram0.bss (NOLOAD) : {
    _bss_start = ABSOLUTE(.);
    *(.bss .bss.*)
    *(COMMON)
    _bss_end = ABSOLUTE(.);
  } > dram0_0_seg

  /* Heap */
  .heap (NOLOAD) : {
    _heap_start = ABSOLUTE(.);
  } > dram0_0_seg

  /* Stack */
  _stack_sentry = ORIGIN(dram0_0_seg) + LENGTH(dram0_0_seg) - 0x2000;
  _stack_start = ORIGIN(dram0_0_seg) + LENGTH(dram0_0_seg);
}
`;
  }

  /**
   * Generate a default/fallback linker script when no config is available
   */
  generateDefault(
    flashSize: number = 65536,
    ramSize: number = 20480,
    flashOrigin: string = "0x08000000",
    ramOrigin: string = "0x20000000",
    entry: string = "Reset_Handler"
  ): string {
    return this.generate({
      memory: {
        regions: {
          FLASH: { origin: flashOrigin, attr: "rx" },
          RAM: { origin: ramOrigin, attr: "rwx" },
        },
        stack: { minSize: 0x400 },
        heap: { minSize: 0x200 },
      },
      linker: {
        entry,
        template: "arm-cortex-m",
      },
      deviceSizes: {
        FLASH: flashSize,
        RAM: ramSize,
      },
    });
  }
}

// Singleton instance
export const linkerScriptGenerator = new LinkerScriptGenerator();
