/**
 * Component Library Types
 *
 * Shared interfaces and types for the modular component library system.
 * These types are used by all component generators and the discovery system.
 */

/**
 * Result returned by all component generators
 */
export interface GeneratorResult {
  /** Complete SVG markup string */
  svg: string;
  /** Component dimensions */
  dimensions: {
    width: number;
    height: number;
  };
  /** Connection points for wiring */
  connectionPoints: ConnectionPointDefinition[];
}

/**
 * Definition of a connection point generated by a component
 */
export interface ConnectionPointDefinition {
  /** Unique identifier within the component */
  id: string;
  /** Human-readable label */
  label: string;
  /** X position relative to component */
  x: number;
  /** Y position relative to component */
  y: number;
  /** Connection point type */
  type: 'power' | 'ground' | 'signal' | 'sense' | 'data';
  /** Optional color override */
  color?: string;
  /** Shape of the connection point */
  shape?: 'circle' | 'rectangle' | 'blade' | 'ring' | 'spade';
  /** Radius/size of the connection point */
  radius?: number;
  /** Optional description/tooltip */
  description?: string;
  /** Voltage at this point */
  voltage?: number;
  /** Current rating in Amps */
  currentRating?: number;
  /** Label offsets */
  labelOffsetX?: number;
  labelOffsetY?: number;
  /** 1-based pin index for the connector/pinout view */
  pinNumber?: number;
  /** Semantic role used by the pinout view */
  signalType?: 'power' | 'ground' | 'signal' | 'data' | 'analog' | 'pwm' | 'rf';
  /** Pin exists in data + pinout view but is not rendered on the canvas */
  hidden?: boolean;
  /** Wires terminating here represent cables, not single conductors */
  isBusPort?: boolean;
  /** For bus ports: IDs of internal (typically hidden) pins this aggregates */
  internalPinIds?: string[];
}

/**
 * Configuration field definition for component config schemas
 */
export interface ConfigField {
  /** Field type */
  type: 'number' | 'string' | 'boolean' | 'select' | 'color' | 'array';
  /** Human-readable label */
  label: string;
  /** Default value */
  default: unknown;
  /** For select type: available options */
  options?: Array<{ value: string | number; label: string }>;
  /** For number type: minimum value */
  min?: number;
  /** For number type: maximum value */
  max?: number;
  /** For number type: step increment */
  step?: number;
  /** For array type: item schema */
  items?: ConfigField;
  /** For array type: minimum number of items */
  minItems?: number;
  /** For array type: maximum number of items */
  maxItems?: number;
  /** For array type: sync length with another number field's value */
  syncWithField?: string;
  /** Help text shown in UI */
  description?: string;
}

/**
 * Component category. Drives the picker sidebar and grouping.
 */
export type ComponentCategory =
  | 'power'
  | 'protection'
  | 'distribution'
  | 'measurement'
  | 'connector'
  | 'relays'
  | 'lighting'
  | 'solar'
  | 'motor-control'
  | 'microcontrollers'
  | 'misc';

/**
 * Component metadata
 */
export interface ComponentMetadata {
  /** Unique component identifier (kebab-case) */
  id: string;
  /** Display name */
  name: string;
  /** Category for grouping in picker */
  category: ComponentCategory;
  /** Brief description */
  description: string;
  /** Configuration schema */
  config: Record<string, ConfigField>;
  /** Search tags */
  tags?: string[];
  /** If true, all connection points share the same electrical net automatically (e.g. bus bars) */
  isCommonBus?: boolean;
  /** Thumbnail image path (optional, uses generated preview if not specified) */
  thumbnail?: string;
}

/**
 * Complete component definition (metadata + generator)
 */
export interface ComponentDefinition {
  /** Component metadata from config.yaml */
  metadata: ComponentMetadata;
  /** Generator function */
  generate: (config: Record<string, unknown>) => GeneratorResult;
  /** Calculate dimensions without generating full SVG */
  getDimensions?: (config: Record<string, unknown>) => { width: number; height: number };
}

/**
 * Category labels and icons for the component picker UI
 */
export const COMPONENT_CATEGORIES: Array<{ id: ComponentCategory; label: string; icon: string }> = [
  { id: 'power', label: 'Power', icon: '🔋' },
  { id: 'distribution', label: 'Distribution', icon: '⚡' },
  { id: 'protection', label: 'Protection', icon: '🛡' },
  { id: 'measurement', label: 'Measurement', icon: '📏' },
  { id: 'relays', label: 'Relays & Switches', icon: '🔌' },
  { id: 'connector', label: 'Connectors', icon: '🔗' },
  { id: 'lighting', label: 'Lighting', icon: '💡' },
  { id: 'solar', label: 'Solar', icon: '☀️' },
  { id: 'motor-control', label: 'Motor Control', icon: '⚙' },
  { id: 'microcontrollers', label: 'Microcontrollers', icon: '🧠' },
  { id: 'misc', label: 'Miscellaneous', icon: '⚛' },
];
