/* CMSIS Version */
#ifndef CMSIS_VERSION_H
#define CMSIS_VERSION_H
#define __CM_CMSIS_VERSION_MAIN (5U)
#define __CM_CMSIS_VERSION_SUB (9U)
#define __CM_CMSIS_VERSION ((__CM_CMSIS_VERSION_MAIN<<16)|__CM_CMSIS_VERSION_SUB)
#endif
